parameters:
    cisco_wsapi.xcdr_server.class:   Invite\Component\Cisco\Wsapi\Server\XcdrServer
    cisco_wsapi.xcdr_client.class:   Invite\Component\Cisco\Wsapi\Client\XcdrClient
    cisco_wsapi.xcdr_listener.class: Invite\Bundle\Cisco\WsapiBundle\EventListener\XcdrListener
        
services:
    cisco_wsapi.xcdr_server:
        class:        "%cisco_wsapi.xcdr_server.class%"
        arguments:    ["@cisco_wsapi.xcdr_listener"]
        
    cisco_wsapi.xcdr_client:
        class:        "%cisco_wsapi.xcdr_client.class%"
        arguments:
           options:
              protocol: "%cisco_wsapi.xcdr.protocol%"
              app_name: "%cisco_wsapi.xcdr.app_name%"
              app_host: "%cisco_wsapi.app_host%"
              app_protocol: "%cisco_wsapi.app_protocol%"
              connection: "%cisco_wsapi.soap.connection_timeout%"
              trace: "%cisco_wsapi.soap.trace%"
              exception: "%cisco_wsapi.soap.exception%"
              socket: "%cisco_wsapi.soap.socket_timeout%"
              cdr_format: "%cisco_wsapi.xcdr.cdr_format%"
          
    cisco_wsapi.xcdr_listener:
        class:        "%cisco_wsapi.xcdr_listener.class%"
        arguments:    ["@event_dispatcher"]